{% set version = '0.7.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-userfriendlyscience
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/userfriendlyscience_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/userfriendlyscience/userfriendlyscience_{{ version }}.tar.gz
  sha256: a49e0c47f4739cb4e3adcbd12199dab457f5aabf5f2797ad392863a460ef599d

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-biasedurn
    - r-diagrammer
    - r-ggally
    - r-gparotation
    - r-mass
    - r-mbess
    - r-rcolorbrewer
    - r-scrt
    - r-suppdists
    - r-xml
    - r-car
    - r-data.tree
    - r-digest
    - r-diptest
    - r-ggplot2
    - r-ggrepel
    - r-ggridges
    - r-gridextra
    - r-gtable
    - r-knitr
    - r-lavaan
    - r-lme4
    - r-minpack.lm
    - r-pander
    - r-plyr
    - r-psych
    - r-pwr
    - r-rio
    - r-scales
    - r-ufs >=0.0.1
    - r-viridis
    - r-xtable
  run:
    - r-base
    - r-biasedurn
    - r-diagrammer
    - r-ggally
    - r-gparotation
    - r-mass
    - r-mbess
    - r-rcolorbrewer
    - r-scrt
    - r-suppdists
    - r-xml
    - r-car
    - r-data.tree
    - r-digest
    - r-diptest
    - r-ggplot2
    - r-ggrepel
    - r-ggridges
    - r-gridextra
    - r-gtable
    - r-knitr
    - r-lavaan
    - r-lme4
    - r-minpack.lm
    - r-pander
    - r-plyr
    - r-psych
    - r-pwr
    - r-rio
    - r-scales
    - r-ufs >=0.0.1
    - r-viridis
    - r-xtable

test:
  commands:
    - $R -e "library('userfriendlyscience')"           # [not win]
    - "\"%R%\" -e \"library('userfriendlyscience')\""  # [win]

about:
  home: http://userfriendlyscience.com
  license: GPL (>= 3)
  summary: Contains a number of functions that serve two goals. First, to make R more accessible
    to people migrating from SPSS by adding a number of functions that behave roughly
    like their SPSS equivalents (also see <https://rosettastats.com>). Second, to make
    a number of slightly more advanced functions more user friendly to relatively novice
    users. The package also conveniently houses a number of additional functions that
    are intended to increase the quality of methodology and statistics in psychology,
    not by offering technical solutions, but by shifting perspectives, for example towards
    reasoning based on sampling distributions as opposed to on point estimates.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: userfriendlyscience
# Type: Package
# Title: Quantitative Analysis Made Accessible
# Version: 0.7.2
# Date: 2018-09-25
# Authors@R: c(person("Gjalt-Jorn", "Peters", email = "gjalt-jorn@userfriendlyscience.com", role = c("aut", "cre", "ctb")), person("Peter", "Verboon", role = c("ctb")), person("James", "Green", role = c("ctb")))
# Maintainer: Gjalt-Jorn Peters <gjalt-jorn@userfriendlyscience.com>
# License: GPL (>= 3)
# Description: Contains a number of functions that serve two goals. First, to make R more accessible to people migrating from SPSS by adding a number of functions that behave roughly like their SPSS equivalents (also see <https://rosettastats.com>). Second, to make a number of slightly more advanced functions more user friendly to relatively novice users. The package also conveniently houses a number of additional functions that are intended to increase the quality of methodology and statistics in psychology, not by offering technical solutions, but by shifting perspectives, for example towards reasoning based on sampling distributions as opposed to on point estimates.
# URL: http://userfriendlyscience.com
# BugReports: https://github.com/matherion/userfriendlyscience/issues
# LazyData: true
# Imports: BiasedUrn, car, data.tree, DiagrammeR, diptest, digest, GGally, ggplot2, ggrepel, ggridges, gridExtra, GPArotation, gtable, knitr, lavaan, lme4, MASS, MBESS, minpack.lm, pander, plyr, psych, pwr, RColorBrewer, rio, scales, SCRT, SuppDists, ufs (>= 0.0.1), viridis, XML, xtable
# Suggests: multcompView
# NeedsCompilation: no
# Packaged: 2018-09-24 16:50:22 UTC; micro
# Author: Gjalt-Jorn Peters [aut, cre, ctb], Peter Verboon [ctb], James Green [ctb]
# Repository: CRAN
# Date/Publication: 2018-09-24 18:30:03 UTC
