travis:
  secure:
    BINSTAR_TOKEN: kVnBWhXYJSynI8rNhQ/yE4rdcwYxm7uNmaDotRuVgvqt8TKmKEe/MBZpxqVH8/fXCQKE/ig5Gszw+QNkT7qAsSRpA53tM3ngLQ77Gw0N21l9fSgwWI0iXdn5w+zpXYIReknRB0EYzJ9RGeew6UcDZnMb1KKPnvFffuB9tfariCejxs5cj/Z/BaI6G/XliZgkwsE3J4gP2qPnHAbEdI9UrnXBHplWLLWAtGd8lXzKMMXyQd8D2Gu+k3EQyrILDOn4J1c0HD+PxolJeWg0Gv9q4hdeehYXmtIdvB6sGFY2xVOqcjpXxFNH9LZM2oSkZbtXIYGWW35tuDz6Atp2r/3OqFujxO6DmRD8nANYIvBXyQ+MISPNDJuR3aQqpnw1D1hDwCgpv5O3ZCSv32o7O2/+DpnsPmTLFaHnC9uAjzgMFOgiJyzDR0PEt6JFF4ijsWfYvqazt/Jgg4NVmL4MiRYeHMfkveeil6ODaExqF6MfrMYctU1M6KdTahR6bt+RrjgyKIXjvHUJrTtiwyDxd6rXJhHYHPWQDqqnlC9nTNUP0WVjtu0+sp7Pf7zDDPpzZ+VCKOjByO36B0tOzVG/i+tVYr6wABhqEvamYj42gQJKcPAOXM0EXTft7uYrXDctjbUCwxVrYPrKJ7gt7G77P4yNa5skz77dCgIpQmUMpQ9MfNo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
